dokuwiki: cosmetic refactor

diff --git a/dokuwiki/imageroot/actions/configure-module/20configure b/dokuwiki/imageroot/actions/configure-module/20configure
--- a/dokuwiki/imageroot/actions/configure-module/20configure
+++ b/dokuwiki/imageroot/actions/configure-module/20configure
@@ -25,30 +25,23 @@ set -e
 # Redirect any output to the journal (stderr)
 exec 1>&2
 
-#1. variabili ambiente DOKUWIKI_HOST -> configuration db esmith (pre-requisiti, non può partire senza), configurazione runtime -> db esmith aggiuntiv
-
-# host -> traefik, -> immagine dokuwiki
-
 # read stdin
 # stdin: "mywiki 8081"
 read wiki_name tcp_port
 
+# Make sure wiki name is not empty
 if [[ -z "${wiki_name}" ]]; then
   # Validation error
-  echo "The wiki name is missing" >&2 # UI TODO: segnalazione campo che fallisce e i18n
+  echo "The wiki name is missing" >&2 # FIXME: use UI validationr protocol
   exit 2
 fi
 
-
-# Parlo con l'agent in ascolto su FD3 
-# Al momento èdisponibile solo il comando set-env
-# I valori diventano persistenti solo se tutti gli step dell'azione terminano con exit 0
-# TODO glossario action vs step
-cat >&3 <<EOF
+# Talk with agent using file descriptor:
+# - save environment variables
+# - dump everything to file
+cat >&${AGENT_COMFD} <<EOF
 set-env WIKI_NAME ${wiki_name}
 set-env TCP_PORT ${tcp_port}
 set-env PHP_ENABLE_OPCACHE 1
 dump-env
 EOF
-
-
